# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

#Base URL
baseurl:          /fifty1lab

# Setup
title:            fifty1lab
tagline:          'A new beginning - fifty1lab' 
description:      'A new home for fifty1lab' 
url:              http://shahzshafie.github.io/
paginate:         5

author:
  name:           'Shah Z. Shafie @ fifty1lab.com'
  url:            https://twitter.com/shahzuhair

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/shahzshafie/fifty1lab
